### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by ACR1209** [izulwahidin/Docker-PocketBase-Multi-Instance#1]
I've tried using this but for some reason the PB is not downloading and obviously I'm getting error on the container.
![image](https://github.com/izulwahidin/Docker-PocketBase-Multi-Instance/assets/78624635/8c9c3c43-0601-433e-b019-5d031839bb11)

OS: Ubuntu 22.04

**Comment by izulwahidin** [comment]
Apologies for the delayed response. Please pull the latest commit and run the services using the following command:

```
./run.sh
```
Let me know if you encounter any issues.

Thank you.
